logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

server:
  port: 8081

identityServiceUri: ${IDENTITY_SERVICE_URI}

jwt:
  publicKey: ${JWT_PUBLIC_KEY}