apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-app
  template:
    metadata:
      labels:
        app: identity-app
    spec:
      containers:
        - name: identity-app
          image: symryvvin/identity:1.0
          envFrom:
            - configMapRef:
                name: identity-app-config
          ports:
            - name: web
              containerPort: 8080